name: CI_CD

on:
  push:
    tags:
      - "*"
    branches:
      - 'main'
      - 'master'

env:
  app_name: cyberchef-app

jobs:
  build-depoly-files:
    name: Build depoly files for ${{ github.ref_name }}
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: CyberChef/package-lock.json
      - name: 'Install dependencies '
        run: |
          npm install
        working-directory: CyberChef
      - name: 'Building'
        run: |
          npm run build
        working-directory: CyberChef
      - name: Prepare build files achive
        run: |
          ls -l ./CyberChef/build/prod/
          # remove the zipped CyberChef file
          rm -rf ./CyberChef/build/prod/CyberChef_*.zip
          ls -l ./CyberChef/build/prod/
          7z a -tzip ${{env.app_name}}-${{ github.ref_name }}.zip -r ./CyberChef/build/prod/*
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: app-dist
          path: ${{env.app_name}}-${{ github.ref_name }}.zip
      - name: 'Publish build files achive to release'
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          file: ${{env.app_name}}-${{ github.ref_name }}.zip
          tags: true
          draft: false
          overwrite: true

  build-native-executable:
    name: 'Build native executable'
    needs: [build-depoly-files]
    if: contains(github.ref, 'tags')
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04', 'macos-latest', 'windows-latest']
        include:
          - os: 'ubuntu-22.04'
            label: 'linux'
            executable_extension: ''
          - os: 'macos-latest'
            label: 'macos'
            executable_extension: ''
          - os: 'windows-latest'
            label: 'windows'
            executable_extension: '.exe'
    runs-on: ${{matrix.os}}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          submodules: false
      - uses: actions/download-artifact@v2
        with:
          name: app-dist
      - name: Extract app-dist
        run: |
          rm -rf dist
          unzip ${{env.app_name}}-${{ github.ref_name }}.zip -d dist
        shell: bash
      - name: Display structure of downloaded files
        run: |
          ls -l . dist
          npx -y --package=tree-node-cli -- treee dist
        shell: bash
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: check toolchain version
        run: |
          node --version
          npm --version
          rustc --version
          cargo --version
      - name: 'Setup for linux'
        if: matrix.os == 'ubuntu-22.04'
        run: |
          # https://ubuntu.com/blog/statement-on-32-bit-i386-packages-for-ubuntu-19-10-and-20-04-lts
          # https://askubuntu.com/questions/1252062/how-to-install-libncurses-so-5-in-ubuntu-20-04
          # https://askubuntu.com/questions/522372/installing-32-bit-libraries-on-ubuntu-14-04-lts-64-bit
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo add-apt-repository universe
          sudo dpkg --add-architecture i386 
          sudo apt update
          sudo apt upgrade
          # install both 32-bit and 64-bit prerequisites of tauri
          # libayatana-appindicator3-dev is the successor of libappindicator3-dev and 64-bit only
          # https://tauri.studio/v1/guides/getting-started/prerequisites/
          sudo apt install -y \
            libwebkit2gtk-4.0-dev \
            libwebkit2gtk-4.0-dev:i386 \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libssl-dev:i386 \
            libgtk-3-dev \
            libgtk-3-dev:i386 \
            patchelf \
            librsvg2-dev \
            librsvg2-dev:i386 \
            libayatana-appindicator3-dev \
            gcc-multilib \
            g++-multilib
          echo 'ok'
      - name: 'Setup for macos'
        if: matrix.os == 'macos-latest'
        run: |
          echo 'ok'
      - name: 'Setup for windows'
        if: matrix.os == 'windows-latest'
        run: |
          # choco install visualstudio2019-workload-vctools
          # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#visual-studio-enterprise-2019
          echo 'ok'
      - name: Build Native binarys on ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: |
          echo "build native binarys..."
          rustup target add x86_64-unknown-linux-gnu
          rustup target add i686-unknown-linux-gnu
          yarn
          yarn tauri info
          yarn tauri build -t x86_64-unknown-linux-gnu -v -c "{\"package\":{\"version\":\"${{ github.ref_name }}\"}}"
          # check ERROR: Could not find dependency: libwebkit2gtk-4.0.so.37 
          # docker run -t --rm -v `pwd`/src-tauri:/src-tauri liudonghua123/cross:x86_64-unknown-linux-gnu-tauri ls -l src-tauri/target/x86_64-unknown-linux-gnu/release/cyberchef-app src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/appimage/cyberchef-app.AppDir/usr/bin/cyberchef-app
          # docker run -t --rm -v `pwd`/src-tauri:/src-tauri liudonghua123/cross:x86_64-unknown-linux-gnu-tauri file src-tauri/target/x86_64-unknown-linux-gnu/release/cyberchef-app src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/appimage/cyberchef-app.AppDir/usr/bin/cyberchef-app
          # docker run -t --rm -v `pwd`/src-tauri:/src-tauri liudonghua123/cross:x86_64-unknown-linux-gnu-tauri ldd src-tauri/target/x86_64-unknown-linux-gnu/release/cyberchef-app src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/appimage/cyberchef-app.AppDir/usr/bin/cyberchef-app
          # (cd src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/appimage && OUTPUT=cyberchef-app_2.1.0_amd64.AppImage ./linuxdeploy-x86_64.AppImage --appimage-extract-and-run --appdir cyberchef-app.AppDir --plugin gtk --output appimage -v0 || true)
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/:$PKG_CONFIG_PATH
          export PKG_CONFIG_SYSROOT_DIR=/
          yarn tauri build -t i686-unknown-linux-gnu -v -c "{\"package\":{\"version\":\"${{ github.ref_name }}\"}}"
          echo "build native binarys finished"
      - name: Build Native binarys on macos
        if: matrix.os == 'macos-latest'
        run: |
          echo "build native binarys..."
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
          yarn
          yarn tauri info
          yarn tauri build -t x86_64-apple-darwin -c "{\"package\":{\"version\":\"${{ github.ref_name }}\"}}"
          yarn tauri build -t aarch64-apple-darwin -c "{\"package\":{\"version\":\"${{ github.ref_name }}\"}}"
          echo "build native binarys finished"
      - name: Build Native binarys on windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "build native binarys..."
          rustup target add x86_64-pc-windows-msvc
          rustup target add i686-pc-windows-msvc
          # if you use cmd shell, you should use call to execute yarn/mvn commands
          # if you pass some arguments contains quotes in powershell, you need to escape it!
          # see https://adamtheautomator.com/powershell-escape-double-quotes/, use '"string"' or "`"string`""
          yarn
          yarn tauri info
          yarn tauri build -t x86_64-pc-windows-msvc -c "{\"package\":{\"version\":\"${{ github.ref_name }}\"}}"
          yarn tauri build -t i686-pc-windows-msvc -c "{\"package\":{\"version\":\"${{ github.ref_name }}\"}}"
          echo "build native binarys finished"
        shell: bash
      - name: Display structure of build files
        continue-on-error: true
        run: |
          npx -y --package=tree-node-cli -- treee src-tauri/target/
        shell: bash

      - name: Prepare release files on ${{matrix.label}}
        continue-on-error: true
        if: matrix.os == 'ubuntu-22.04'
        run: |
          # for 64-bit binary
          mv src-tauri/target/x86_64-unknown-linux-gnu/release/${{env.app_name}}${{matrix.executable_extension}} ${{env.app_name}}-${{matrix.label}}-${{ github.ref_name }}_amd64${{matrix.executable_extension}}
          mv src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/appimage/${{env.app_name}}_${{ github.ref_name }}_amd64.AppImage ${{env.app_name}}-${{matrix.label}}-${{ github.ref_name }}_amd64.AppImage
          mv src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/deb/${{env.app_name}}_${{ github.ref_name }}_amd64.deb ${{env.app_name}}-${{matrix.label}}-${{ github.ref_name }}_amd64.deb
          # for 32-bit binary
          mv src-tauri/target/i686-unknown-linux-gnu/release/${{env.app_name}}${{matrix.executable_extension}} ${{env.app_name}}-${{matrix.label}}-${{ github.ref_name }}_i386${{matrix.executable_extension}}
          mv src-tauri/target/i686-unknown-linux-gnu/release/bundle/appimage/${{env.app_name}}_${{ github.ref_name }}_i386.AppImage ${{env.app_name}}-${{matrix.label}}-${{ github.ref_name }}_i386.AppImage
          mv src-tauri/target/i686-unknown-linux-gnu/release/bundle/deb/${{env.app_name}}_${{ github.ref_name }}_i386.deb ${{env.app_name}}-${{matrix.label}}-${{ github.ref_name }}_i386.deb
        shell: bash
      - name: Prepare release files on ${{matrix.label}}
        continue-on-error: true
        if: matrix.os == 'macos-latest'
        run: |
          mv src-tauri/target/x86_64-apple-darwin/release/${{env.app_name}}${{matrix.executable_extension}} ${{env.app_name}}-${{matrix.label}}-${{ github.ref_name }}_x64${{matrix.executable_extension}}
          mv src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/${{env.app_name}}_${{ github.ref_name }}_x64.dmg ${{env.app_name}}-${{matrix.label}}-${{ github.ref_name }}_x64.dmg
          7z a -tzip ${{env.app_name}}-${{matrix.label}}-${{ github.ref_name }}_x64.app.zip ./src-tauri/target/x86_64-apple-darwin/release/bundle/macos/${{env.app_name}}.app
          mv src-tauri/target/aarch64-apple-darwin/release/${{env.app_name}}${{matrix.executable_extension}} ${{env.app_name}}-${{matrix.label}}-${{ github.ref_name }}_aarch64${{matrix.executable_extension}}
          mv src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/${{env.app_name}}_${{ github.ref_name }}_aarch64.dmg ${{env.app_name}}-${{matrix.label}}-${{ github.ref_name }}_aarch64.dmg
          7z a -tzip ${{env.app_name}}-${{matrix.label}}-${{ github.ref_name }}_aarch64.app.zip ./src-tauri/target/aarch64-apple-darwin/release/bundle/macos/${{env.app_name}}.app
        shell: bash
      - name: Prepare release files on ${{matrix.label}}
        continue-on-error: true
        if: matrix.os == 'windows-latest'
        run: |
          mv src-tauri/target/x86_64-pc-windows-msvc/release/${{env.app_name}}${{matrix.executable_extension}} ${{env.app_name}}-${{matrix.label}}-${{ github.ref_name }}_x64${{matrix.executable_extension}}
          mv src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/${{env.app_name}}_${{ github.ref_name }}_x64_en-US.msi ${{env.app_name}}-${{matrix.label}}-${{ github.ref_name }}_x64.msi
          mv src-tauri/target/i686-pc-windows-msvc/release/${{env.app_name}}${{matrix.executable_extension}} ${{env.app_name}}-${{matrix.label}}-${{ github.ref_name }}_x86${{matrix.executable_extension}}
          mv src-tauri/target/i686-pc-windows-msvc/release/bundle/msi/${{env.app_name}}_${{ github.ref_name }}_x86_en-US.msi ${{env.app_name}}-${{matrix.label}}-${{ github.ref_name }}_x86.msi
        shell: bash
      - name: Display structure of build files
        run: |
          ls -l .
        shell: bash
        
      - name: 'Publish binary to release'
        continue-on-error: true
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          file: ${{env.app_name}}-${{matrix.label}}-${{ github.ref_name }}*
          tags: true
          draft: false
          overwrite: true